### ISSUE TITLE
Multilang support

### ISSUE THREAD

**Issue by ViBE-HU** [gpawru/touchpad#1]
Please add multilang support.

**Comment by gpawru** [comment]
sure! added to my to-do list

**Comment by gpawru** [comment]
@ViBE-HU Added language support. However, since I only speak Russian/English, I didn't risk making translations myself. Currently, only Russian and English are available. Localization files can be found in the repository: po/ru.po, po/en.po. If you have 5 minutes to translate a dozen phrases into your language, I'd be very grateful (and will add the localization right away).

**Comment by ViBE-HU** [comment]
No worries. The community will gather up and do their part.

My translation is on the way. But I wait the update first. I would like to check my work before I add the commit.

**Comment by ViBE-HU** [comment]
Not sure what's going on, but I still don't get the update. I'm on Ubuntu 24.04. Are these related maybe?
![rejected](https://github.com/user-attachments/assets/800328cb-7a28-4bb7-b52f-b5b66e41d784)

**Comment by gpawru** [comment]
@ViBE-HU fixed, reviewed!

**Comment by ViBE-HU** [comment]
Nice. Tested. I think it's time to close the issue. Thanks!
